apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.clusterName }}
  description: GKE cluster for ${{ values.clusterName }}
  annotations:
    argocd/app-name:  gcp-infrastructure
spec:
  type: resource
  lifecycle: development
  system: back-stack
  owner: group:platform-engineering
  links:
    - url: https://console.cloud.google.com/kubernetes/clusters/details/${{ values.region }}/${{ values.clusterName }}
      title: GKE Console