apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-container-${{ values.clusterName }} 
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-container:v1.8.0