apiVersion: compositions.io/v1alpha1
kind: XCluster
metadata:
  name: ${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: gcp-provider-config  # Propagate the providerConfigRef here
  parameters:
    clusterName: ${{ values.clusterName }}
    region: ${{ values.region }}
    machineType: ${{ values.machineType }}
    nodeCount: ${{ values.nodeCount }}
  compositionRef:
    name: gke-cluster-nodepool